### ISSUE TITLE
support for older isodat .caf filetype?

### ISSUE THREAD

**Issue by japhir** [sebkopf/isoread#21]
Hi! I was wondering if someone already struggled with parsing the old filetype from isodat, `.caf`. We're running a MAT-253 and can read in the `.scn` files it produces, but not the `.caf` files.

If not, could anyone walk me through how I would go about it? I've been looking at your `parse_binary_data` functions from the helper file, but I guess it takes a while to dig into what you have already set up as a framework.

See attached example, which I had to zip for GitHub to allow me to upload it (also, it makes it 90% smaller).

[example.zip](https://github.com/sebkopf/isoread/files/1458198/example.zip)

**Comment by sebkopf** [comment]
Hi Ilja, thanks for sending the example file! could you also share the actual voltage data that is stored in this file by any chance via manual export from isodat? that would be very helpful for figuring out what's different about the .caf file and where the data is stored. Parsing the binary files from isodat is a bit tricky, but if you want to take a stab yourself I recommend using a good hex editor (e.g. [010 editor](https://www.sweetscape.com/010editor/)) to take a look at the file structure first. In terms of implementation, isoread has mostly (except scn files) been ported to the newer package [isoreader](https://github.com/kopflab/isoreader) which has a cleaner interface and should make implementation of new file formats a lot more straight forward. Sorry, the vignettes for isoreader are still in the works.

**Comment by japhir** [comment]
Hi Sebastian,

Our lab PC with Isodat is far, far away, so I'll get the Isodat export later. ;-).

Here's a file—possibly a different one, because I renamed it and didn't find the original—with an ETH-1 .caf file, as well as what Easotope is able to extract from it (.xlsx). This includes raw voltages per cycle.

**Comment by japhir** [comment]
Hi again,

I've finally found the time to include a raw .caf file, along with the isodat .csv export and the easotope .xls file: 

[170612_Ilja_ETH-3-0005.zip](https://github.com/sebkopf/isoread/files/1491479/170612_Ilja_ETH-3-0005.zip)

isoreader looks very promising!

I was wondering if there has been any progress since the ICIW meeting regarding integration of all the different efforts to get our data out of the nasty isodat binaries. We discussed that it might be nice to learn a bit from each other, and have the python, R, and Java (easotope) people join forces a bit. Do you know anything about this?

**Comment by sebkopf** [comment]
Hi Ilja, awesome, this was super helpful! .caf seems to be a strange hybrid between .did and .cf in terms of data structure.

Okay, isoreader now has full support for .caf files (raw data, file info, resistors, standards, pre-computed data table) - I'm attaching a processing file for your data (raw Rmd and compiled HTML). See if it works for you with the latest version of [isoreader](https://github.com/kopflab/isoreader) (0.9.2). 

[ilja_caf_test.zip](https://github.com/sebkopf/isoread/files/1507998/ilja_caf_test.zip)

Two questions:
1. since robustness testing is pretty much for an n=1, would you be willing to test this for a few more of your .caf files? (you can feed an entire folder name to isoreader and it'll take in all compatible file types)
2. would you be willing to supply a sample .caf file I can bundle with the isoreader package? (I have examples included for .did, .cf, .dxf and .iarc but have never generated a .caf myself).

A couple of notes on isoreader. It's in late beta-testing for a candidate to go on CRAN (so any bug reports most welcome!) with scan files the only missing major file type I still want to include in version 1.0 (other formats will have to wait for now). I am only vaguely aware of the ICIW effort because I'm not actually a clumper myself (my lab specializes in more traditional compound-specific continuous flow) but I think I know what you are referring to from conversations with Max Lloyd (@maxmansaxman) and I think it's a great idea to think about a data format for storing and exchanging IRMS data between the different systems. Isoreader currently has built in support for export to Feather for easy exchange with python and of course export to Excel - would be great to add whatever file formats the ICIW crowd converges on (perhaps an XML self-descriptive format or a traditional relational database structure)? 

Overall, isoreader is primarily intended as a one-stop-shop command line tool to read all kinds of IRMS data files and does not do data processing itself (except for voltage to current conversions and a few quick overview plotting functions). It plugs into my own processing pipe-lines but those tend to be application specific so they live in separate packages. Although the original motivation for isoread and isoreader was primarily to access continuous flow data, the new implementation has a fairly straight forward framework and works well for capturing dual inlet data as well - so I very much welcome the new file formats.
